using Godot;
using System;
using System.Collections.Generic;

public class ComputerCPU : VBoxContainer {
    public override void _Ready() {
        var yes = (PackedScene)ResourceLoader.Load("res://Scenes/NewProducts/ComputerCPUButton.tscn");
        List<List<object>> cpus = new List<List<object>>();
        #region ohio 30 day trial
        for (int i = Global.CustomChip.Count - 1; i >= 0 ; i--) {
            Product chip = Global.CustomChip[i];
            // moneyspent is used to store the cpu's price cuz yes
            cpus.Add(new List<object>{Global.CompanyName, chip.Name, chip.Rating.ToString(), chip.MoneySpent.ToString()});
        }
        if (Global.Year == 1) {
            cpus.Add(new List<object>{"In Tells", "u9 13th gen", "10", "600"});
            cpus.Add(new List<object>{"In Tells", "u7 13th gen", "9", "400"});
            cpus.Add(new List<object>{"In Tells", "u5 13th gen", "8", "300"});
            cpus.Add(new List<object>{"In Tells", "u3 13th gen", "7", "100"});
            cpus.Add(new List<object>{"In Tells", "u9 10th gen", "9", "300"});
            cpus.Add(new List<object>{"In Tells", "u7 10th gen", "8", "200"});
            cpus.Add(new List<object>{"In Tells", "u5 10th gen", "7", "125"});
            cpus.Add(new List<object>{"In Tells", "u3 10th gen", "6", "75"});
            cpus.Add(new List<object>{"In Tells", "u7 7th gen", "7", "300"});
            cpus.Add(new List<object>{"In Tells", "u5 7th gen", "6", "150"});
            cpus.Add(new List<object>{"In Tells", "u3 7th gen", "5", "100"});
            cpus.Add(new List<object>{"In Tells", "u7 3rd gen", "4", "135"});
            cpus.Add(new List<object>{"In Tells", "u5 3rd gen", "3", "100"});
            cpus.Add(new List<object>{"In Tells", "u3 3rd gen", "2", "50"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "10", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "9", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "8", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "9", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "8", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "7", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 3000", "8", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 3000", "7", "275"});
            cpus.Add(new List<object>{"AND", "Rise 5 3000", "6", "200"});
            cpus.Add(new List<object>{"AND", "Rise 3 3000", "5", "150"});
        } else if (Global.Year == 2) {
            cpus.Add(new List<object>{"In Tells", "u9 14th gen", "10", "700"});
            cpus.Add(new List<object>{"In Tells", "u7 14th gen", "9", "500"});
            cpus.Add(new List<object>{"In Tells", "u5 14th gen", "8", "400"});
            cpus.Add(new List<object>{"In Tells", "u3 14th gen", "7", "300"});
            cpus.Add(new List<object>{"In Tells", "u9 13th gen", "9", "600"});
            cpus.Add(new List<object>{"In Tells", "u7 13th gen", "8", "400"});
            cpus.Add(new List<object>{"In Tells", "u5 13th gen", "7", "300"});
            cpus.Add(new List<object>{"In Tells", "u3 13th gen", "6", "100"});
            cpus.Add(new List<object>{"In Tells", "u9 10th gen", "8", "300"});
            cpus.Add(new List<object>{"In Tells", "u7 10th gen", "7", "200"});
            cpus.Add(new List<object>{"In Tells", "u5 10th gen", "6", "125"});
            cpus.Add(new List<object>{"In Tells", "u3 10th gen", "5", "75"});
            cpus.Add(new List<object>{"In Tells", "u7 7th gen", "6", "300"});
            cpus.Add(new List<object>{"In Tells", "u5 7th gen", "5", "150"});
            cpus.Add(new List<object>{"In Tells", "u3 7th gen", "4", "100"});
            cpus.Add(new List<object>{"In Tells", "u7 3rd gen", "3", "135"});
            cpus.Add(new List<object>{"In Tells", "u5 3rd gen", "2", "100"});
            cpus.Add(new List<object>{"In Tells", "u3 3rd gen", "1", "50"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "10", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "9", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "8", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "9", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "8", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "7", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "8", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "7", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "6", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 3000", "7", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 3000", "6", "275"});
            cpus.Add(new List<object>{"AND", "Rise 5 3000", "5", "200"});
            cpus.Add(new List<object>{"AND", "Rise 3 3000", "4", "150"});
        } else if (Global.Year == 3) {
            cpus.Add(new List<object>{"In Tells", "u9 15th gen", "10", "800"});
            cpus.Add(new List<object>{"In Tells", "u7 15th gen", "9", "600"});
            cpus.Add(new List<object>{"In Tells", "u5 15th gen", "8", "500"});
            cpus.Add(new List<object>{"In Tells", "u3 15th gen", "7", "400"});
            cpus.Add(new List<object>{"In Tells", "u9 14th gen", "9", "700"});
            cpus.Add(new List<object>{"In Tells", "u7 14th gen", "8", "500"});
            cpus.Add(new List<object>{"In Tells", "u5 14th gen", "7", "400"});
            cpus.Add(new List<object>{"In Tells", "u3 14th gen", "6", "300"});
            cpus.Add(new List<object>{"In Tells", "u9 13th gen", "8", "600"});
            cpus.Add(new List<object>{"In Tells", "u7 13th gen", "7", "400"});
            cpus.Add(new List<object>{"In Tells", "u5 13th gen", "6", "300"});
            cpus.Add(new List<object>{"In Tells", "u3 13th gen", "5", "100"});
            cpus.Add(new List<object>{"In Tells", "u9 10th gen", "7", "300"});
            cpus.Add(new List<object>{"In Tells", "u7 10th gen", "6", "200"});
            cpus.Add(new List<object>{"In Tells", "u5 10th gen", "5", "125"});
            cpus.Add(new List<object>{"In Tells", "u3 10th gen", "4", "75"});
            cpus.Add(new List<object>{"In Tells", "u7 7th gen", "5", "300"});
            cpus.Add(new List<object>{"In Tells", "u5 7th gen", "4", "150"});
            cpus.Add(new List<object>{"In Tells", "u3 7th gen", "3", "100"});
            cpus.Add(new List<object>{"In Tells", "u7 3rd gen", "2", "135"});
            cpus.Add(new List<object>{"In Tells", "u5 3rd gen", "1", "100"});
            cpus.Add(new List<object>{"In Tells", "u3 3rd gen", "0", "50"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "10", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "9", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "8", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "9", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "8", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "7", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "8", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "7", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "6", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "7", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "6", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "5", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 3000", "6", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 3000", "5", "275"});
            cpus.Add(new List<object>{"AND", "Rise 5 3000", "4", "200"});
            cpus.Add(new List<object>{"AND", "Rise 3 3000", "3", "150"});
        } else if (Global.Year == 4) {
            cpus.Add(new List<object>{"In Tells", "u9 16th gen", "10", "900"});
            cpus.Add(new List<object>{"In Tells", "u7 16th gen", "9", "700"});
            cpus.Add(new List<object>{"In Tells", "u5 16th gen", "8", "600"});
            cpus.Add(new List<object>{"In Tells", "u3 16th gen", "7", "500"});
            cpus.Add(new List<object>{"In Tells", "u9 15th gen", "9", "800"});
            cpus.Add(new List<object>{"In Tells", "u7 15th gen", "8", "600"});
            cpus.Add(new List<object>{"In Tells", "u5 15th gen", "7", "500"});
            cpus.Add(new List<object>{"In Tells", "u3 15th gen", "6", "400"});
            cpus.Add(new List<object>{"In Tells", "u9 14th gen", "8", "700"});
            cpus.Add(new List<object>{"In Tells", "u7 14th gen", "7", "500"});
            cpus.Add(new List<object>{"In Tells", "u5 14th gen", "6", "400"});
            cpus.Add(new List<object>{"In Tells", "u3 14th gen", "5", "300"});
            cpus.Add(new List<object>{"In Tells", "u9 13th gen", "7", "600"});
            cpus.Add(new List<object>{"In Tells", "u7 13th gen", "6", "400"});
            cpus.Add(new List<object>{"In Tells", "u5 13th gen", "5", "300"});
            cpus.Add(new List<object>{"In Tells", "u3 13th gen", "4", "100"});
            cpus.Add(new List<object>{"In Tells", "u9 10th gen", "6", "300"});
            cpus.Add(new List<object>{"In Tells", "u7 10th gen", "5", "200"});
            cpus.Add(new List<object>{"In Tells", "u5 10th gen", "4", "125"});
            cpus.Add(new List<object>{"In Tells", "u3 10th gen", "3", "75"});
            cpus.Add(new List<object>{"In Tells", "u7 7th gen", "4", "300"});
            cpus.Add(new List<object>{"In Tells", "u5 7th gen", "3", "150"});
            cpus.Add(new List<object>{"In Tells", "u3 7th gen", "2", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "10", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "9", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "8", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "9", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "8", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "7", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "8", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "7", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "6", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "7", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "6", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "5", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "6", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "5", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "4", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 3000", "5", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 3000", "4", "275"});
            cpus.Add(new List<object>{"AND", "Rise 5 3000", "3", "200"});
            cpus.Add(new List<object>{"AND", "Rise 3 3000", "2", "150"});
        } else if (Global.Year == 5) {
            cpus.Add(new List<object>{"In Tells", "Onion u9 1st gen", "10", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 1st gen", "9", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 1st gen", "8", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 1st gen", "7", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 17th gen", "9", "1000"});
            cpus.Add(new List<object>{"In Tells", "Core u7 17th gen", "8", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u5 17th gen", "7", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u3 17th gen", "6", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 16th gen", "8", "900"});
            cpus.Add(new List<object>{"In Tells", "Core u7 16th gen", "7", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u5 16th gen", "6", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u3 16th gen", "5", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u9 15th gen", "7", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u7 15th gen", "6", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u5 15th gen", "5", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u3 15th gen", "4", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u9 14th gen", "6", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u7 14th gen", "5", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u5 14th gen", "4", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u3 14th gen", "3", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u9 13th gen", "5", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u7 13th gen", "4", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u5 13th gen", "3", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u3 13th gen", "2", "100"});
            cpus.Add(new List<object>{"In Tells", "Core u9 10th gen", "4", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u7 10th gen", "3", "200"});
            cpus.Add(new List<object>{"In Tells", "Core u5 10th gen", "2", "125"});
            cpus.Add(new List<object>{"In Tells", "Core u3 10th gen", "1", "75"});
            cpus.Add(new List<object>{"In Tells", "Core u7 7th gen", "2", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u5 7th gen", "1", "150"});
            cpus.Add(new List<object>{"In Tells", "Core u3 7th gen", "0", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 11K", "10", "900"});
            cpus.Add(new List<object>{"AND", "Rise 7 11K", "9", "700"});
            cpus.Add(new List<object>{"AND", "Rise 5 11K", "8", "600"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "9", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "8", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "7", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "8", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "7", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "6", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "7", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "6", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "5", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "6", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "5", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "4", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "5", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "4", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "3", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 3000", "4", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 3000", "3", "275"});
            cpus.Add(new List<object>{"AND", "Rise 5 3000", "2", "200"});
            cpus.Add(new List<object>{"AND", "Rise 3 3000", "1", "150"});
        } else if (Global.Year == 6) {
            cpus.Add(new List<object>{"In Tells", "Onion u9 2nd gen", "10", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 2nd gen", "9", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 2nd gen", "8", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 2nd gen", "7", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 1st gen", "9", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 1st gen", "8", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 1st gen", "7", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 1st gen", "6", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 17th gen", "8", "1000"});
            cpus.Add(new List<object>{"In Tells", "Core u7 17th gen", "7", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u5 17th gen", "6", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u3 17th gen", "5", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 16th gen", "7", "900"});
            cpus.Add(new List<object>{"In Tells", "Core u7 16th gen", "6", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u5 16th gen", "5", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u3 16th gen", "4", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u9 15th gen", "6", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u7 15th gen", "5", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u5 15th gen", "4", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u3 15th gen", "3", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u9 14th gen", "5", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u7 14th gen", "4", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u5 14th gen", "3", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u3 14th gen", "2", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u9 13th gen", "4", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u7 13th gen", "3", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u5 13th gen", "2", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u3 13th gen", "1", "100"});
            cpus.Add(new List<object>{"In Tells", "Core u9 10th gen", "3", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u7 10th gen", "2", "200"});
            cpus.Add(new List<object>{"In Tells", "Core u5 10th gen", "1", "125"});
            cpus.Add(new List<object>{"In Tells", "Core u3 10th gen", "0", "75"});
            cpus.Add(new List<object>{"AND", "Cheese 9 1K", "10", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 7 1K", "9", "900"});
            cpus.Add(new List<object>{"AND", "Cheese 5 1K", "8", "800"});
            cpus.Add(new List<object>{"AND", "Rise 9 11K", "9", "900"});
            cpus.Add(new List<object>{"AND", "Rise 7 11K", "8", "700"});
            cpus.Add(new List<object>{"AND", "Rise 5 11K", "7", "600"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "8", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "7", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "6", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "7", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "6", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "5", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "6", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "5", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "4", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "5", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "4", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "3", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "4", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "3", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "2", "100"});
            cpus.Add(new List<object>{"AND", "Rise 9 3000", "3", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 3000", "2", "275"});
            cpus.Add(new List<object>{"AND", "Rise 5 3000", "1", "200"});
            cpus.Add(new List<object>{"AND", "Rise 3 3000", "0", "150"});
        } else if (Global.Year == 7) {
            cpus.Add(new List<object>{"In Tells", "Onion u9 3rd gen", "10", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 3rd gen", "9", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 3rd gen", "8", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 3rd gen", "7", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 2nd gen", "9", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 2nd gen", "8", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 2nd gen", "7", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 2nd gen", "6", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 1st gen", "8", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 1st gen", "7", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 1st gen", "6", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 1st gen", "5", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 17th gen", "7", "1000"});
            cpus.Add(new List<object>{"In Tells", "Core u7 17th gen", "6", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u5 17th gen", "5", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u3 17th gen", "4", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 16th gen", "6", "900"});
            cpus.Add(new List<object>{"In Tells", "Core u7 16th gen", "5", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u5 16th gen", "4", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u3 16th gen", "3", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u9 15th gen", "5", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u7 15th gen", "4", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u5 15th gen", "3", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u3 15th gen", "2", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u9 14th gen", "4", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u7 14th gen", "3", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u5 14th gen", "2", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u3 14th gen", "1", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u9 13th gen", "3", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u7 13th gen", "2", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u5 13th gen", "1", "300"});
            cpus.Add(new List<object>{"In Tells", "Core u3 13th gen", "0", "100"});
            cpus.Add(new List<object>{"AND", "Cheese 9 2K", "10", "1300"});
            cpus.Add(new List<object>{"AND", "Cheese 7 2K", "9", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 5 2K", "8", "1000"});
            cpus.Add(new List<object>{"AND", "Cheese 9 1K", "9", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 7 1K", "8", "900"});
            cpus.Add(new List<object>{"AND", "Cheese 5 1K", "7", "800"});
            cpus.Add(new List<object>{"AND", "Rise 9 11K", "8", "900"});
            cpus.Add(new List<object>{"AND", "Rise 7 11K", "7", "700"});
            cpus.Add(new List<object>{"AND", "Rise 5 11K", "6", "600"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "7", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "6", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "5", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "6", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "5", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "4", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "5", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "4", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "3", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "4", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "3", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "2", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "3", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "2", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "1", "100"});
        } else if (Global.Year == 8) {
            cpus.Add(new List<object>{"In Tells", "Onion u9 4th gen", "10", "1800"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 4th gen", "9", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 4th gen", "8", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 4th gen", "7", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 3rd gen", "9", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 3rd gen", "8", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 3rd gen", "7", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 3rd gen", "6", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 2nd gen", "8", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 2nd gen", "7", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 2nd gen", "6", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 2nd gen", "5", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 1st gen", "7", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 1st gen", "6", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 1st gen", "5", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 1st gen", "4", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 17th gen", "6", "1000"});
            cpus.Add(new List<object>{"In Tells", "Core u7 17th gen", "5", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u5 17th gen", "4", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u3 17th gen", "3", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 16th gen", "5", "900"});
            cpus.Add(new List<object>{"In Tells", "Core u7 16th gen", "4", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u5 16th gen", "3", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u3 16th gen", "2", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u9 15th gen", "4", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u7 15th gen", "3", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u5 15th gen", "2", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u3 15th gen", "1", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u9 14th gen", "3", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u7 14th gen", "2", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u5 14th gen", "1", "400"});
            cpus.Add(new List<object>{"In Tells", "Core u3 14th gen", "0", "300"});
            cpus.Add(new List<object>{"AND", "Cheese 9 3K", "10", "1600"});
            cpus.Add(new List<object>{"AND", "Cheese 7 3K", "9", "1400"});
            cpus.Add(new List<object>{"AND", "Cheese 5 3K", "8", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 9 2K", "9", "1300"});
            cpus.Add(new List<object>{"AND", "Cheese 7 2K", "8", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 5 2K", "7", "1000"});
            cpus.Add(new List<object>{"AND", "Cheese 9 1K", "8", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 7 1K", "7", "900"});
            cpus.Add(new List<object>{"AND", "Cheese 5 1K", "6", "800"});
            cpus.Add(new List<object>{"AND", "Rise 9 11K", "7", "900"});
            cpus.Add(new List<object>{"AND", "Rise 7 11K", "6", "700"});
            cpus.Add(new List<object>{"AND", "Rise 5 11K", "5", "600"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "6", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "5", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "4", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "5", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "4", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "3", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "4", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "3", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "2", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "3", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "2", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "1", "200"});
            cpus.Add(new List<object>{"AND", "Rise 9 5000", "2", "300"});
            cpus.Add(new List<object>{"AND", "Rise 7 5000", "1", "200"});
            cpus.Add(new List<object>{"AND", "Rise 5 5000", "0", "100"});
        } else if (Global.Year == 9) {
            cpus.Add(new List<object>{"In Tells", "Onion u9 5th gen", "10", "2000"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 5th gen", "9", "1800"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 5th gen", "8", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 5th gen", "7", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 4th gen", "9", "1800"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 4th gen", "8", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 4th gen", "7", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 4th gen", "6", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 3rd gen", "8", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 3rd gen", "7", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 3rd gen", "6", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 3rd gen", "5", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 2nd gen", "7", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 2nd gen", "6", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 2nd gen", "5", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 2nd gen", "4", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 1st gen", "6", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 1st gen", "5", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 1st gen", "4", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 1st gen", "3", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 17th gen", "5", "1000"});
            cpus.Add(new List<object>{"In Tells", "Core u7 17th gen", "4", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u5 17th gen", "3", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u3 17th gen", "2", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 16th gen", "4", "900"});
            cpus.Add(new List<object>{"In Tells", "Core u7 16th gen", "3", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u5 16th gen", "2", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u3 16th gen", "1", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u9 15th gen", "3", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u7 15th gen", "2", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u5 15th gen", "1", "500"});
            cpus.Add(new List<object>{"In Tells", "Core u3 15th gen", "0", "400"});
            cpus.Add(new List<object>{"AND", "Cheese 9 4K", "10", "1800"});
            cpus.Add(new List<object>{"AND", "Cheese 7 4K", "9", "1600"});
            cpus.Add(new List<object>{"AND", "Cheese 5 4K", "8", "1400"});
            cpus.Add(new List<object>{"AND", "Cheese 9 3K", "9", "1600"});
            cpus.Add(new List<object>{"AND", "Cheese 7 3K", "8", "1400"});
            cpus.Add(new List<object>{"AND", "Cheese 5 3K", "7", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 9 2K", "8", "1300"});
            cpus.Add(new List<object>{"AND", "Cheese 7 2K", "7", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 5 2K", "6", "1000"});
            cpus.Add(new List<object>{"AND", "Cheese 9 1K", "7", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 7 1K", "6", "900"});
            cpus.Add(new List<object>{"AND", "Cheese 5 1K", "5", "800"});
            cpus.Add(new List<object>{"AND", "Rise 9 11K", "6", "900"});
            cpus.Add(new List<object>{"AND", "Rise 7 11K", "5", "700"});
            cpus.Add(new List<object>{"AND", "Rise 5 11K", "4", "600"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "5", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "4", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "3", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "4", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "3", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "2", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "3", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "2", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "1", "300"});
            cpus.Add(new List<object>{"AND", "Rise 9 7000", "2", "500"});
            cpus.Add(new List<object>{"AND", "Rise 7 7000", "1", "300"});
            cpus.Add(new List<object>{"AND", "Rise 5 7000", "0", "200"});
            cpus.Add(new List<object>{"Pineapple", "Mark 9 Furiously Fast", "10", "2000"});
            cpus.Add(new List<object>{"Pineapple", "Mark 9 Furious", "9", "2200"});
            cpus.Add(new List<object>{"Pineapple", "Mark 9 Fast", "8", "2400"});
        } else if (Global.Year > 9) {
            cpus.Add(new List<object>{"In Tells", "Onion u9 6th gen", "10", "2200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 6th gen", "9", "2000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 6th gen", "8", "1800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 6th gen", "7", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 5th gen", "9", "2000"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 5th gen", "8", "1800"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 5th gen", "7", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 5th gen", "6", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 4th gen", "8", "1800"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 4th gen", "7", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 4th gen", "6", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 4th gen", "5", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 3rd gen", "7", "1600"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 3rd gen", "6", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 3rd gen", "5", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 3rd gen", "4", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 2nd gen", "6", "1400"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 2nd gen", "5", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 2nd gen", "4", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 2nd gen", "3", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u9 1st gen", "5", "1200"});
            cpus.Add(new List<object>{"In Tells", "Onion u7 1st gen", "4", "1000"});
            cpus.Add(new List<object>{"In Tells", "Onion u5 1st gen", "3", "800"});
            cpus.Add(new List<object>{"In Tells", "Onion u3 1st gen", "2", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 17th gen", "4", "1000"});
            cpus.Add(new List<object>{"In Tells", "Core u7 17th gen", "3", "800"});
            cpus.Add(new List<object>{"In Tells", "Core u5 17th gen", "2", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u3 17th gen", "1", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u9 16th gen", "3", "900"});
            cpus.Add(new List<object>{"In Tells", "Core u7 16th gen", "2", "700"});
            cpus.Add(new List<object>{"In Tells", "Core u5 16th gen", "1", "600"});
            cpus.Add(new List<object>{"In Tells", "Core u3 16th gen", "0", "500"});
            cpus.Add(new List<object>{"AND", "Cheese 9 5K", "10", "2000"});
            cpus.Add(new List<object>{"AND", "Cheese 7 5K", "9", "1800"});
            cpus.Add(new List<object>{"AND", "Cheese 5 5K", "8", "1600"});
            cpus.Add(new List<object>{"AND", "Cheese 9 4K", "9", "1800"});
            cpus.Add(new List<object>{"AND", "Cheese 7 4K", "8", "1600"});
            cpus.Add(new List<object>{"AND", "Cheese 5 4K", "7", "1400"});
            cpus.Add(new List<object>{"AND", "Cheese 9 3K", "8", "1600"});
            cpus.Add(new List<object>{"AND", "Cheese 7 3K", "7", "1400"});
            cpus.Add(new List<object>{"AND", "Cheese 5 3K", "6", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 9 2K", "7", "1300"});
            cpus.Add(new List<object>{"AND", "Cheese 7 2K", "6", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 5 2K", "5", "1000"});
            cpus.Add(new List<object>{"AND", "Cheese 9 1K", "6", "1100"});
            cpus.Add(new List<object>{"AND", "Cheese 7 1K", "5", "900"});
            cpus.Add(new List<object>{"AND", "Cheese 5 1K", "4", "800"});
            cpus.Add(new List<object>{"AND", "Rise 9 11K", "5", "900"});
            cpus.Add(new List<object>{"AND", "Rise 7 11K", "4", "700"});
            cpus.Add(new List<object>{"AND", "Rise 5 11K", "3", "600"});
            cpus.Add(new List<object>{"AND", "Rise 9 10K", "4", "800"});
            cpus.Add(new List<object>{"AND", "Rise 7 10K", "3", "600"});
            cpus.Add(new List<object>{"AND", "Rise 5 10K", "2", "500"});
            cpus.Add(new List<object>{"AND", "Rise 9 9000", "3", "700"});
            cpus.Add(new List<object>{"AND", "Rise 7 9000", "2", "500"});
            cpus.Add(new List<object>{"AND", "Rise 5 9000", "1", "400"});
            cpus.Add(new List<object>{"AND", "Rise 9 8000", "2", "600"});
            cpus.Add(new List<object>{"AND", "Rise 7 8000", "1", "400"});
            cpus.Add(new List<object>{"AND", "Rise 5 8000", "0", "300"});
            cpus.Add(new List<object>{"Pineapple", "Mark 10 Furiously Fast", "10", "1000"});
            cpus.Add(new List<object>{"Pineapple", "Mark 10 Furious", "9", "2000"});
            cpus.Add(new List<object>{"Pineapple", "Mark 10 Fast", "8", "4000"});
            cpus.Add(new List<object>{"Pineapple", "Mark 9 Furiously Fast", "9", "2000"});
            cpus.Add(new List<object>{"Pineapple", "Mark 9 Furious", "8", "2200"});
            cpus.Add(new List<object>{"Pineapple", "Mark 9 Fast", "7", "2400"});
        }
        #endregion

        // make epic buttons
        foreach (var item in cpus) {
            var OK = (ComputerCPUButton)yes.Instance();
            OK.Init(item);
            AddChild(OK);
        }

        base._Ready();
    }
}
