using Godot;
using System;

public class BenjaminDoverText : Label {
    public override void _Ready() {
        string[] companiesThatCanBeSued = {
            "Conglomerate of Buffets",
            "Cool Oil Company",
            "Bank That Chases Money",
            "Amazing.com",
            "Pineapple",
            "Bank of States",
            "Tatoyo Motors",
            "Goggles",
            "Macrohard",
            "Sam's Song Group",
            "Epic Oil Company",
            "Casing Oil",
            "Horizon Communications",
            "AC&C",
            "United States of Healthcare",
            "Wall Mart",
            "People's Cars",
            "City Bank",
            "Tendollar Holdings",
            "Castcom",
            "Amazingchineseproducts.com",
            "Databook Platforms",
            "Golden Sacks Group",
            "Johns's Sons",
            "No's Ten",
            "In Tells",
            "Sonia",
            "Taiwan Delicious Chip Manufacturing",
            "Fard Motors",
            "Petrobruh",
            "American Delivery",
            "PopsiCo",
            "Walt Dosney",
            "Eye Bee M",
            "Capital Two",
            "Cola-Cola",
            "Mystic",
            "AIRPLANE",
            "Priceco Wholesale",
            "Galaxy Lever",
            "Vision",
            "Goal Store",
            "Meloncars",
            "Deer & Company",
            "Wallofgreen",
            "DarkStone",
            "Delete Technologies",
            "Bruhdesco Bank",
            "Napdragon",
            "Le Real",
            "Novideo",
            "Nice Shoes",
            "PayFriend",
            "Donald Burgers",
            "Netfilms",
            "Brazilian Bank",
            "Master of Cards",
            "Show Me Phones",
            "Stellar Bucks",
            "Life's Great",
            "Parahill",
            "Adubious Software",
            "Very Cool Meat",
            "Nokey",
            "Boing Airplanes",
            "MovieTek",
            "No Entiendo",
            "AND",
            "Silly Co",
            "Scamco",
            "Bagged Air",
            "Robert Tech",
            "Deliciousness Company",
        };
        Random sorandomomglolhaha = new Random();
        // sorry
        Text = $"Hello, {Global.CeoName}. Here's 10 companies I sued this month:\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\n- {companiesThatCanBeSued[sorandomomglolhaha.Next(0,companiesThatCanBeSued.Length)]}\nWe got ${String.Format("{0:n0}", (int)Global.Money/20)} from the lawsuits!";
        base._Ready();
    }
}
